// ============================================================
// AIRPORT CAR TAXI — Shared Data & Constants
// ============================================================

export const COMPANY = {
  name: 'Airport Car Taxi',
  tagline: 'Reliable Airport Transfers Across the UK',
  email: 'airporttravelcar@gmail.com',
  address: 'London, United Kingdom',
  googleRating: 4.9,
  reviewCount: 1847,
  yearsOperating: 12,
};

export const AIRPORTS = [
  {
    slug: 'heathrow',
    name: 'Heathrow Airport',
    code: 'LHR',
    location: 'London',
    description: 'The UK\'s busiest airport and a major global hub, located 15 miles west of central London.',
    terminals: ['T1', 'T2', 'T3', 'T4', 'T5'],
    topRoutes: ['London', 'Oxford', 'Cambridge', 'Brighton', 'Windsor'],
    priceFrom: 35,
    image: '/images/airports/heathrow.jpg',
    meta: {
      title: 'Heathrow Airport Taxi | Fixed Price Airport Transfers | Airport Car Taxi',
      description: 'Book a reliable Heathrow airport taxi with fixed prices. Professional drivers, flight monitoring & 24/7 service. Instant quote for Heathrow transfers.',
    },
  },
  {
    slug: 'gatwick',
    name: 'Gatwick Airport',
    code: 'LGW',
    location: 'Crawley, West Sussex',
    description: 'The UK\'s second-busiest airport, located 28 miles south of central London.',
    terminals: ['North', 'South'],
    topRoutes: ['London', 'Brighton', 'Guildford', 'Crawley', 'Reigate'],
    priceFrom: 45,
    image: '/images/airports/gatwick.jpg',
    meta: {
      title: 'Gatwick Airport Taxi | Fixed Price Transfers | Airport Car Taxi',
      description: 'Reliable Gatwick airport taxi transfers with fixed prices. Flight tracking, professional drivers & 24/7 availability. Book your Gatwick taxi online.',
    },
  },
  {
    slug: 'manchester',
    name: 'Manchester Airport',
    code: 'MAN',
    location: 'Manchester',
    description: 'The largest airport outside London, serving the North of England and beyond.',
    terminals: ['T1', 'T2', 'T3'],
    topRoutes: ['Manchester City Centre', 'Liverpool', 'Leeds', 'Sheffield', 'Bolton'],
    priceFrom: 30,
    image: '/images/airports/manchester.jpg',
    meta: {
      title: 'Manchester Airport Taxi | Fixed Price Transfers | Airport Car Taxi',
      description: 'Book a Manchester airport taxi at fixed prices. Professional drivers, flight monitoring & meet & greet. Instant quote for Manchester airport transfers.',
    },
  },
  {
    slug: 'luton',
    name: 'Luton Airport',
    code: 'LTN',
    location: 'Luton, Bedfordshire',
    description: 'A major London airport serving budget carriers, located 35 miles north of central London.',
    terminals: ['Main Terminal'],
    topRoutes: ['London', 'Luton', 'Milton Keynes', 'Bedford', 'Northampton'],
    priceFrom: 40,
    image: '/images/airports/luton.jpg',
    meta: {
      title: 'Luton Airport Taxi | Fixed Price Airport Transfers | Airport Car Taxi',
      description: 'Reliable Luton airport taxi with fixed prices. 24/7 service, professional drivers & flight monitoring. Book your Luton airport transfer today.',
    },
  },
  {
    slug: 'stansted',
    name: 'Stansted Airport',
    code: 'STN',
    location: 'Stansted, Essex',
    description: 'London\'s fourth-largest airport, located 35 miles northeast of central London.',
    terminals: ['Main Terminal'],
    topRoutes: ['London', 'Cambridge', 'Chelmsford', 'Colchester', 'Ipswich'],
    priceFrom: 45,
    image: '/images/airports/stansted.jpg',
    meta: {
      title: 'Stansted Airport Taxi | Fixed Price Transfers | Airport Car Taxi',
      description: 'Book a Stansted airport taxi with fixed prices. Professional drivers, flight tracking & 24/7 availability. Instant quote for Stansted airport transfers.',
    },
  },
  {
    slug: 'birmingham',
    name: 'Birmingham Airport',
    code: 'BHX',
    location: 'Birmingham',
    description: 'The UK\'s third-largest airport, serving the Midlands and surrounding regions.',
    terminals: ['Main Terminal'],
    topRoutes: ['Birmingham City', 'Coventry', 'Solihull', 'Wolverhampton', 'Leicester'],
    priceFrom: 28,
    image: '/images/airports/birmingham.jpg',
    meta: {
      title: 'Birmingham Airport Taxi | Fixed Price Transfers | Airport Car Taxi',
      description: 'Reliable Birmingham airport taxi at fixed prices. Professional drivers, flight monitoring & 24/7 service. Book your Birmingham airport transfer now.',
    },
  },
];

export const VEHICLES = [
  {
    id: 'standard',
    name: 'Standard Saloon',
    category: 'Economy',
    passengers: 4,
    luggage: 2,
    description: 'Comfortable, clean saloon cars perfect for solo travellers or couples. Ideal for standard airport transfers.',
    features: ['Air Conditioning', 'Free Wi-Fi', 'Phone Charger', 'Flight Tracking'],
    priceMultiplier: 1.0,
    icon: '🚗',
    image: '/images/vehicles/saloon.jpg',
  },
  {
    id: 'executive',
    name: 'Executive Car',
    category: 'Business',
    passengers: 4,
    luggage: 3,
    description: 'Premium executive vehicles including Mercedes E-Class and BMW 5 Series for a superior travel experience.',
    features: ['Leather Seats', 'Air Conditioning', 'Free Wi-Fi', 'Newspapers', 'Phone Charger'],
    priceMultiplier: 1.4,
    icon: '🚙',
    image: '/images/vehicles/executive.jpg',
  },
  {
    id: 'mpv',
    name: 'MPV 6-Seater',
    category: 'Family',
    passengers: 6,
    luggage: 6,
    description: 'Spacious multi-purpose vehicles, perfect for families or groups travelling with lots of luggage.',
    features: ['Spacious Interior', 'Air Conditioning', 'Free Wi-Fi', 'Extra Luggage Space'],
    priceMultiplier: 1.5,
    icon: '🚐',
    image: '/images/vehicles/mpv.jpg',
  },
  {
    id: 'minibus',
    name: 'Minibus 8-Seater',
    category: 'Group',
    passengers: 8,
    luggage: 8,
    description: 'Large minibuses perfect for corporate groups, sporting events, or large family travel.',
    features: ['8 Passenger Seats', 'Large Boot Space', 'Air Conditioning', 'Free Wi-Fi'],
    priceMultiplier: 1.8,
    icon: '🚌',
    image: '/images/vehicles/minibus.jpg',
  },
  {
    id: 'luxury',
    name: 'Luxury Chauffeur',
    category: 'Premium',
    passengers: 4,
    luggage: 3,
    description: 'Arrive in style with our luxury chauffeur service. Mercedes S-Class, Rolls Royce or equivalent.',
    features: ['Professional Chauffeur', 'Champagne', 'Red Carpet Service', 'Premium Leather', 'Free Wi-Fi'],
    priceMultiplier: 2.5,
    icon: '🏆',
    image: '/images/vehicles/luxury.jpg',
  },
];

export const ROUTES = [
  {
    slug: 'heathrow-to-london-taxi',
    from: 'Heathrow Airport',
    to: 'London City Centre',
    distance: '15 miles',
    travelTime: '30-50 minutes',
    priceFrom: 45,
    description: 'Our most popular route — fast, reliable transfers between Heathrow Airport and Central London.',
    faqs: [
      { q: 'How long does Heathrow to London take?', a: 'The journey from Heathrow Airport to Central London typically takes 30-50 minutes depending on traffic, with faster times outside of peak hours.' },
      { q: 'What is the fixed price for a Heathrow to London taxi?', a: 'Our fixed prices start from £45 for a standard saloon car. The price includes all tolls and there are no hidden charges.' },
      { q: 'Do you offer meet and greet at Heathrow?', a: 'Yes, our drivers will meet you inside the terminal with a name board after tracking your flight. No extra waiting charges if your flight is delayed.' },
    ],
  },
  {
    slug: 'heathrow-to-oxford-taxi',
    from: 'Heathrow Airport',
    to: 'Oxford',
    distance: '35 miles',
    travelTime: '45-70 minutes',
    priceFrom: 75,
    description: 'Comfortable, fixed-price taxi transfers between Heathrow Airport and the beautiful city of Oxford.',
    faqs: [
      { q: 'How far is Heathrow to Oxford?', a: 'Heathrow Airport to Oxford is approximately 35 miles and takes between 45-70 minutes depending on traffic conditions.' },
      { q: 'Is a taxi from Heathrow to Oxford expensive?', a: 'Our fixed-price fares start from £75 for a standard saloon — often cheaper and far more convenient than other options for groups or families.' },
      { q: 'Can you pick me up from any Oxford address?', a: 'Yes, we offer door-to-door service to any address in Oxford, including the University colleges, hotels, and residential areas.' },
    ],
  },
  {
    slug: 'heathrow-to-cambridge-taxi',
    from: 'Heathrow Airport',
    to: 'Cambridge',
    distance: '65 miles',
    travelTime: '70-90 minutes',
    priceFrom: 110,
    description: 'Direct, comfortable taxi transfers from Heathrow Airport to Cambridge with no changes or waiting.',
    faqs: [
      { q: 'How long is the journey from Heathrow to Cambridge?', a: 'The journey from Heathrow Airport to Cambridge is approximately 65 miles and takes 70-90 minutes depending on traffic.' },
      { q: 'What is the best way to get from Heathrow to Cambridge?', a: 'A private taxi is the most convenient and direct option, especially for families or those with lots of luggage. It\'s door-to-door with no changes.' },
      { q: 'Do you cover all Cambridge areas?', a: 'Yes, we cover all Cambridge addresses including the city centre, University of Cambridge, Science Park, and surrounding villages.' },
    ],
  },
  {
    slug: 'gatwick-to-london-taxi',
    from: 'Gatwick Airport',
    to: 'London City Centre',
    distance: '28 miles',
    travelTime: '40-60 minutes',
    priceFrom: 60,
    description: 'Reliable, fixed-price taxi transfers from Gatwick Airport to Central London and all areas.',
    faqs: [
      { q: 'How long does Gatwick to London take by taxi?', a: 'The journey typically takes 40-60 minutes depending on traffic and your destination within London.' },
      { q: 'How much is a taxi from Gatwick to Central London?', a: 'Our fixed fares start from £60 for a standard saloon. Prices are fixed regardless of traffic delays.' },
      { q: 'Do drivers meet and greet at Gatwick?', a: 'Yes, our drivers track your flight and wait in the arrivals hall with your name board. No extra charge for delays.' },
    ],
  },
  {
    slug: 'gatwick-to-brighton-taxi',
    from: 'Gatwick Airport',
    to: 'Brighton',
    distance: '30 miles',
    travelTime: '35-50 minutes',
    priceFrom: 55,
    description: 'Fast, comfortable taxi transfers between Gatwick Airport and Brighton with fixed prices.',
    faqs: [
      { q: 'How far is Gatwick from Brighton?', a: 'Gatwick Airport is approximately 30 miles from Brighton, with the journey taking 35-50 minutes.' },
      { q: 'What is the best way to get from Gatwick to Brighton?', a: 'A private taxi offers the most direct and comfortable journey. Fixed prices mean no surprises, and we stop at any address in Brighton.' },
      { q: 'Is Gatwick to Brighton taxi cheaper than the train?', a: 'For groups of 2+ people, taxi is often cheaper than multiple train tickets and much more convenient with luggage.' },
    ],
  },
  {
    slug: 'manchester-airport-to-liverpool-taxi',
    from: 'Manchester Airport',
    to: 'Liverpool',
    distance: '35 miles',
    travelTime: '40-60 minutes',
    priceFrom: 70,
    description: 'Comfortable, fixed-price taxi transfers from Manchester Airport to Liverpool city centre and beyond.',
    faqs: [
      { q: 'How long does Manchester Airport to Liverpool take?', a: 'The journey typically takes 40-60 minutes, covering approximately 35 miles via the M62 motorway.' },
      { q: 'Can I book a taxi from Manchester Airport to Liverpool hotel?', a: 'Yes, we offer door-to-door service to any Liverpool address including hotels, Lime Street, docks, and suburbs.' },
      { q: 'Is there a fixed price from Manchester Airport to Liverpool?', a: 'Yes, our prices are fully fixed from £70 for a standard vehicle. No meter charges, no traffic surcharges.' },
    ],
  },
];

export const BLOG_POSTS = [
  {
    slug: 'best-way-to-get-from-heathrow-to-london',
    title: 'Best Way to Get From Heathrow to London in 2025',
    excerpt: 'Comparing all transport options — Underground, taxi, bus, and private hire — to help you choose the best way to travel from Heathrow Airport to London.',
    category: 'Airport Travel Tips',
    readTime: '6 min read',
    date: '2025-03-10',
    image: '/images/blog/heathrow-london.jpg',
  },
  {
    slug: 'how-much-is-a-heathrow-airport-taxi',
    title: 'How Much Is a Heathrow Airport Taxi? (2025 Price Guide)',
    excerpt: 'A complete breakdown of Heathrow airport taxi prices for every major destination, including central London, Oxford, and more.',
    category: 'Airport Travel Tips',
    readTime: '5 min read',
    date: '2025-03-05',
    image: '/images/blog/taxi-prices.jpg',
  },
  {
    slug: 'heathrow-vs-gatwick-which-airport-is-better',
    title: 'Heathrow vs Gatwick: Which Airport Is Better for Your Trip?',
    excerpt: 'A detailed comparison of Heathrow and Gatwick airports to help you decide which is the better option for your travel itinerary.',
    category: 'UK Travel Guides',
    readTime: '7 min read',
    date: '2025-02-28',
    image: '/images/blog/heathrow-vs-gatwick.jpg',
  },
  {
    slug: 'tips-for-stress-free-airport-transfers',
    title: '10 Tips for a Stress-Free Airport Transfer',
    excerpt: 'Expert tips to make your next airport transfer smooth, punctual, and completely stress-free — from booking to arrival.',
    category: 'Airport Transfer Guides',
    readTime: '5 min read',
    date: '2025-02-20',
    image: '/images/blog/stress-free.jpg',
  },
  {
    slug: 'cheap-heathrow-airport-taxi-guide',
    title: 'How to Find a Cheap Heathrow Airport Taxi (Without Compromising on Quality)',
    excerpt: 'Smart tips for finding affordable Heathrow airport taxis that are still reliable, safe, and comfortable.',
    category: 'Airport Travel Tips',
    readTime: '5 min read',
    date: '2025-02-15',
    image: '/images/blog/cheap-taxi.jpg',
  },
  {
    slug: 'private-airport-transfer-vs-public-transport',
    title: 'Private Airport Transfer vs Public Transport: Which Is Right for You?',
    excerpt: 'We break down the costs, convenience, and comfort of private airport taxis versus trains, buses, and the London Underground.',
    category: 'Airport Transfer Guides',
    readTime: '6 min read',
    date: '2025-02-10',
    image: '/images/blog/private-vs-public.jpg',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Sarah M.',
    location: 'London',
    rating: 5,
    text: 'Used Airport Car Taxi for my Heathrow transfer and the service was exceptional. Driver was early, professional, and the car was spotless. Will definitely use again!',
    service: 'Heathrow Airport Transfer',
  },
  {
    name: 'James R.',
    location: 'Manchester',
    rating: 5,
    text: 'Brilliant service from Manchester Airport to Liverpool. Fixed price, no surprises, and the driver tracked our flight delay perfectly. Highly recommend.',
    service: 'Manchester Airport Transfer',
  },
  {
    name: 'Emma T.',
    location: 'Oxford',
    rating: 5,
    text: 'Our go-to airport transfer company. We use them for all our Heathrow to Oxford trips. Always reliable, always on time. 5 stars every time.',
    service: 'Heathrow to Oxford Transfer',
  },
  {
    name: 'David L.',
    location: 'Birmingham',
    rating: 5,
    text: 'Booked an executive car for a business trip from Birmingham Airport. Immaculate Mercedes, professional chauffeur. Exactly what we needed.',
    service: 'Birmingham Airport Executive',
  },
  {
    name: 'Sophie W.',
    location: 'Brighton',
    rating: 5,
    text: 'Took a family of 5 from Gatwick to Brighton in the MPV. Plenty of space, great driver, and a very fair price. The kids loved it!',
    service: 'Gatwick to Brighton Transfer',
  },
  {
    name: 'Michael P.',
    location: 'Cambridge',
    rating: 5,
    text: 'Needed a late-night transfer from Stansted to Cambridge. Airport Car Taxi delivered perfectly — punctual, courteous, and excellent value.',
    service: 'Stansted to Cambridge Transfer',
  },
];

export const TRUST_FEATURES = [
  { icon: '🕐', title: '24/7 Service', desc: 'Available round the clock, 365 days a year' },
  { icon: '✈️', title: 'Flight Monitoring', desc: 'We track your flight and adjust pickup times automatically' },
  { icon: '💷', title: 'Fixed Prices', desc: 'No hidden charges, no meters, no surprises' },
  { icon: '👔', title: 'Pro Drivers', desc: 'DBS checked, licensed, and experienced professionals' },
  { icon: '🚗', title: 'Clean Vehicles', desc: 'Modern, well-maintained fleet of premium vehicles' },
  { icon: '📱', title: 'Easy Booking', desc: 'Book online in minutes with instant confirmation' },
];
